version: '3.9'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"  # dev exposure
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-test
    command: ["./init.sh", "db", "--", "python", "manage.py", "test"]
    volumes:
      - web_data:/web
    ports:
      - "8000"
    env_file:
      - .env.postgres
      - .env.django

volumes:
  web_data:
