version: '3.9'

services:

  db:
      image: postgres
      ports:
        - "5432:5432"  # dev exposure
      volumes:
        - ./data/db:/var/lib/postgresql/data
      env_file:
        - .env.postgres

  web:
    build: ./web
    command: ["./init.sh", "db", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./web:/web
    ports:
      - "8000:8000"
    env_file:
      - .env.postgres
      - .env.django
      - .env.digital_ocean
    depends_on:
      - db

  app:
    build: ./app
    entrypoint: ["./init.sh", "web", "8000", "--", "python", "taxon_tracker.py"]
    volumes:
      - ./app:/app
    env_file:
      - .env.taxon_tracker
      - .env.postgres
    depends_on:
      - web

  # Documentation
  mdbook:
    container_name: mdbook
    image: peaceiris/mdbook:v0.4.15           # Minimum image
    # image: peaceiris/mdbook:v0.x.x-rust     # `mdbook test` subcommand is available
    # image: ghcr.io/peaceiris/mdbook:v0.x.x  # Docker images on GitHub Packages
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./docs:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'
