# Generated by Django 4.0.4 on 2022-05-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accession_numbers',
            fields=[
                ('accession_number', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('passed_filter', models.BooleanField(null=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_fetched', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='taxons',
            fields=[
                ('taxon_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_fetched', models.DateTimeField(auto_now_add=True)),
                ('accession_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.accession_numbers')),
            ],
        ),
        migrations.AddField(
            model_name='accession_numbers',
            name='taxon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.taxons'),
        ),
    ]
