# Generated by Django 4.0.4 on 2022-05-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession_numbers',
            name='time_fetched',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taxons',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
